apiVersion: image.toolkit.fluxcd.io/v1beta1
kind: ImagePolicy
metadata:
  name: sre-challenge-policy
  namespace: flux-system
spec:
  filterTags:
    pattern: '^v?[0-9]+(\.[0-9]+)*$'
  imageRepositoryRef:
    name: sre-challenge-image
  policy:
    semver:
      range: '>=1.0.0'
