apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sre-challenge-kustomization
  namespace: flux-system
spec:
  interval: 1m
  path: ./k8s
  prune: true
  sourceRef:
    kind: GitRepository
    name: sre-challenge-repo
  targetNamespace: sre-challenge-app
  validation: client
