---
apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sre-challenge-policy
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sre-challenge-img
  policy:
    semver:
      range: '>=1.0.0'
