name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  code_quality:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      - name: Run flake8 (Code Quality Check)
        run: flake8 src/ --count --select=E9,F63,F7,F82 --show-source --statistics

  docker_build:
    runs-on: ubuntu-latest
    needs: code_quality
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image with GitHub SHA tag
        run: |
          docker build -t jmuachifi/sre-challenge-fluxcd:latest -t jmuachifi/sre-challenge-fluxcd:${{ github.sha }} .

  security_check:
    runs-on: ubuntu-latest
    needs: docker_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Trivy Security Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          image-ref: jmuachifi/sre-challenge-fluxcd:${{ github.sha }}

  docker_publish:
    runs-on: ubuntu-latest
    needs: security_check
    steps:
      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image (latest and SHA tag)
        run: |
          docker push jmuachifi/sre-challenge-fluxcd:latest
          docker push jmuachifi/sre-challenge-fluxcd:${{ github.sha }}
